name: flutter_note_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  time_pickerr: ^1.0.6
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  jalali_table_calendar: ^1.1.2+1
  flutter_svg: ^2.0.4
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3  


flutter:

  uses-material-design: true


  assets:
   - images/

  fonts:
    - family: SM
      fonts:
        - asset: asset/fonts/ShabnamMedium.ttf
          weight: 700
  

